openapi: "3.0.0"
info:
  title: Ecommerce App store
  description: writing docs
  version: 1.1.0
  contact:
    email: marcelo.dev.coder@gmail.com
    url: ''

# servers:
#   - url: "https://localhost:3000/api/v1"    
#     description: from local host - secure
#   - url: "https://localhost:3000/api/v1"    
#     description: from local host - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"    
    descriptions: for local host
    variables: 
      version: 
        enum:
          - v1
          - v2
        default: v1
      protocol: 
        enum:
          - http
          - https
        default: http  

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths: 
  /dummy:
    get:
      tags:
        - Home
      summary: returns a message
      responses: 
        200:
          description: success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request      
        500:  
          description: Internal server error